### ISSUE TITLE
multisig.boba.network lags behind chain

### ISSUE THREAD

**Issue by jet86** [bobanetwork/multisig#1]
The user interface at multisig.boba.network still shows transactions as pending for a long time after they are confirmed and showing on the block explorer.

If there's only one tx in the queue it's not a huge problem (though it's still annoying, and not a great user experience), but when there are multiple txs they have to be done in sequence, so it causes a very painful delay...

**Comment by InoMurko** [comment]
Rinkeby or Mainnet?

**Comment by jet86** [comment]
Mainnet. I haven't tested Rinkeby - @bobachad ?

**Comment by jet86** [comment]
I believe this has always been the case, FWIW - https://github.com/omgnetwork/safe-gnosis/issues/1

**Comment by InoMurko** [comment]
safe-transaction-service (the one that syncs rinkeby boba and mainnet boba) got updated. the margin for ETH_REORG_BLOCKS  is now 10 (not 100 anymore).
so if there’s any traffic on boba it should happen fairly immediately. ie the frontend should sync.

if this persists next time please:
- check your last signature transaction block number on explorer
- wait 10 blocks, if frontend still doesn’t update, let me know because it's probably something else at fault :-)

**Comment by InoMurko** [comment]
Apparently this has not been resolved. Reopening

**Comment by InoMurko** [comment]
Looking if it's a bug 
https://github.com/safe-global/safe-react/issues/3937

**Comment by InoMurko** [comment]
It seems like having a more aggressive cache invalidation values helped (in the safe-client-gateway)?!
```
- Name: SAFE_INFO_CACHE_DURATION
              Value: 5000
            - Name: ADDRESS_INFO_CACHE_DURATION
              Value: 5000
            - Name: TOKEN_INFO_CACHE_DURATION
              Value: 5000
            - Name: CHAIN_INFO_CACHE_DURATION
              Value: 100000
            - Name: CHAIN_INFO_RESPONSE_CACHE_DURATION
              Value: 5000
            - Name: EXCHANGE_API_CACHE_DURATION
              Value: 15000
            - Name: REQUEST_CACHE_DURATION
              Value: 5000
            - Name: ABOUT_CACHE_DURATION
              Value: 5000
            - Name: BALANCES_REQUEST_CACHE_DURATION
              Value: 15000
            - Name: REQS_ERROR_CACHE_DURATION
              Value: 5000
            - Name: OWNERS_FOR_SAFES_CACHE_DURATION
              Value: 5000
            - Name: INDEFINITE_TIMEOUT
              Value: 5000
            - Name: SHORT_ERROR_DURATION
              Value: 5000
            - Name: LONG_ERROR_DURATION
              Value: 5000
            - Name: SAFE_APPS_CACHE_DURATION
              Value: 5000
            - Name: TX_QUEUED_CACHE_DURATION
              Value: 5000
```
I've tried and it did help.

@Boyuan-Chen @jet86 please re-open if not fixed :)
